services:
  db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
      POSTGRES_DB: electricity
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_HOST: db # Use the service name 'db' to connect to the database
      DB_PORT: 5432
      DB_USER: academy
      DB_PASSWORD: academy
      DB_NAME: electricity
    ports:
      - 3001:3000
    depends_on:
      - db